### ISSUE TITLE
Is more like a question than an issue, how to indicate if a meeting is virtual?

### ISSUE THREAD

**Issue by IWCMoussaS** [InforMEA/odata.provider#9]
Is more like a question than issue, how to indicate if a meeting is virtual?
From those views:
-- informea_meetings
-- informea_meetings_description
-- informea_meetings_title

Cheers

**Comment by IWCMoussaS** [comment]
virtual | bool | no |   | Yes/No: Distinguish between virtual meetings and physical meetings

**Comment by cristiroma** [comment]
I have added a new `virtual` field in the exposed service and also is supported in the SQL views

- Checkout https://odata.informea.org/informea.svc/Meetings('7dc73998-3c00-41fe-88c1-6f1e3e2faceb') `<d:Virtual>false</d:Virtual>`
- To add support in view - https://github.com/InforMEA/odata.provider/blob/master/etc/informea_odata.sql#L65

You must use 2.6.0 WAR for this.

**Comment by IWCMoussaS** [comment]
Thank you
I have updated to version 2.6.0 and now I can the "virtual" option!
Cheers
